# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/clk104_spi_mux.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_2/design_1_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_2 || ORIG_REF_NAME==design_1_axi_smc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_99M_1/design_1_rst_ps8_0_99M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_1 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1_1/design_1_axi_smc_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1_1 || ORIG_REF_NAME==design_1_axi_smc_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_0/design_1_axis_data_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_0 || ORIG_REF_NAME==design_1_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lfm_tdm_gen_0_0/design_1_lfm_tdm_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lfm_tdm_gen_0_0 || ORIG_REF_NAME==design_1_lfm_tdm_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_1_0/design_1_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_1_0 || ORIG_REF_NAME==design_1_system_ila_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_usp_rf_data_converter_0_0/design_1_usp_rf_data_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_usp_rf_data_converter_0_0 || ORIG_REF_NAME==design_1_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_1 || ORIG_REF_NAME==design_1_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_clock_converter_0_0/design_1_axis_clock_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_clock_converter_0_0 || ORIG_REF_NAME==design_1_axis_clock_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_iq_to_real_0_0/design_1_iq_to_real_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_iq_to_real_0_0 || ORIG_REF_NAME==design_1_iq_to_real_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_clock_converter_1_0/design_1_axis_clock_converter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_clock_converter_1_0 || ORIG_REF_NAME==design_1_axis_clock_converter_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_packetizer_0_0/design_1_adc_packetizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adc_packetizer_0_0 || ORIG_REF_NAME==design_1_adc_packetizer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_2_0/design_1_system_ila_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_2_0 || ORIG_REF_NAME==design_1_system_ila_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rfdc_resetn_and_0/design_1_rfdc_resetn_and_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rfdc_resetn_and_0 || ORIG_REF_NAME==design_1_rfdc_resetn_and_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_adc2_0/design_1_clk_wiz_adc2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_adc2_0 || ORIG_REF_NAME==design_1_clk_wiz_adc2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_dac0_0/design_1_clk_wiz_dac0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_dac0_0 || ORIG_REF_NAME==design_1_clk_wiz_dac0_0} -quiet] -quiet

# XDC: c:/TDM_0704/TDM_0704/TDM_0704.gen/sources_1/bd/design_1/design_1_ooc.xdc
