// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="iq_to_real_iq_to_real,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu48dr-fsvg1517-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=0.532000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=26,HLS_VERSION=2024_2}" *)

module iq_to_real (
        ap_clk,
        ap_rst_n,
        s_axis_iq_TDATA,
        s_axis_iq_TVALID,
        s_axis_iq_TREADY,
        s_axis_iq_TKEEP,
        s_axis_iq_TSTRB,
        s_axis_iq_TLAST,
        m_axis_real_TDATA,
        m_axis_real_TVALID,
        m_axis_real_TREADY
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input  [31:0] s_axis_iq_TDATA;
input   s_axis_iq_TVALID;
output   s_axis_iq_TREADY;
input  [3:0] s_axis_iq_TKEEP;
input  [3:0] s_axis_iq_TSTRB;
input  [0:0] s_axis_iq_TLAST;
output  [15:0] m_axis_real_TDATA;
output   m_axis_real_TVALID;
input   m_axis_real_TREADY;

 reg    ap_rst_n_inv;
reg    s_axis_iq_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0;
reg    m_axis_real_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    regslice_both_m_axis_real_U_apdone_blk;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_01001;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_s_axis_iq_V_data_V_U_apdone_blk;
wire   [31:0] s_axis_iq_TDATA_int_regslice;
wire    s_axis_iq_TVALID_int_regslice;
reg    s_axis_iq_TREADY_int_regslice;
wire    regslice_both_s_axis_iq_V_data_V_U_ack_in;
wire    regslice_both_s_axis_iq_V_keep_V_U_apdone_blk;
wire   [3:0] s_axis_iq_TKEEP_int_regslice;
wire    regslice_both_s_axis_iq_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_iq_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_iq_V_strb_V_U_apdone_blk;
wire   [3:0] s_axis_iq_TSTRB_int_regslice;
wire    regslice_both_s_axis_iq_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_iq_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_iq_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_iq_TLAST_int_regslice;
wire    regslice_both_s_axis_iq_V_last_V_U_vld_out;
wire    regslice_both_s_axis_iq_V_last_V_U_ack_in;
wire   [15:0] m_axis_real_TDATA_int_regslice;
reg    m_axis_real_TVALID_int_regslice;
wire    m_axis_real_TREADY_int_regslice;
wire    regslice_both_m_axis_real_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

iq_to_real_regslice_both #(
    .DataWidth( 32 ))
regslice_both_s_axis_iq_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_iq_TDATA),
    .vld_in(s_axis_iq_TVALID),
    .ack_in(regslice_both_s_axis_iq_V_data_V_U_ack_in),
    .data_out(s_axis_iq_TDATA_int_regslice),
    .vld_out(s_axis_iq_TVALID_int_regslice),
    .ack_out(s_axis_iq_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_iq_V_data_V_U_apdone_blk)
);

iq_to_real_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_iq_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_iq_TKEEP),
    .vld_in(s_axis_iq_TVALID),
    .ack_in(regslice_both_s_axis_iq_V_keep_V_U_ack_in),
    .data_out(s_axis_iq_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_iq_V_keep_V_U_vld_out),
    .ack_out(s_axis_iq_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_iq_V_keep_V_U_apdone_blk)
);

iq_to_real_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_iq_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_iq_TSTRB),
    .vld_in(s_axis_iq_TVALID),
    .ack_in(regslice_both_s_axis_iq_V_strb_V_U_ack_in),
    .data_out(s_axis_iq_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_iq_V_strb_V_U_vld_out),
    .ack_out(s_axis_iq_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_iq_V_strb_V_U_apdone_blk)
);

iq_to_real_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_iq_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_iq_TLAST),
    .vld_in(s_axis_iq_TVALID),
    .ack_in(regslice_both_s_axis_iq_V_last_V_U_ack_in),
    .data_out(s_axis_iq_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_iq_V_last_V_U_vld_out),
    .ack_out(s_axis_iq_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_iq_V_last_V_U_apdone_blk)
);

iq_to_real_regslice_both #(
    .DataWidth( 16 ))
regslice_both_m_axis_real_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_real_TDATA_int_regslice),
    .vld_in(m_axis_real_TVALID_int_regslice),
    .ack_in(m_axis_real_TREADY_int_regslice),
    .data_out(m_axis_real_TDATA),
    .vld_out(regslice_both_m_axis_real_U_vld_out),
    .ack_out(m_axis_real_TREADY),
    .apdone_blk(regslice_both_m_axis_real_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        m_axis_real_TDATA_blk_n = m_axis_real_TREADY_int_regslice;
    end else begin
        m_axis_real_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_real_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_real_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_iq_TDATA_blk_n = s_axis_iq_TVALID_int_regslice;
    end else begin
        s_axis_iq_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_iq_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_iq_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((1'b1 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((1'b1 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((1'b1 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((m_axis_real_TREADY_int_regslice == 1'b0) | (s_axis_iq_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((regslice_both_m_axis_real_U_apdone_blk == 1'b1) | (m_axis_real_TREADY_int_regslice == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign m_axis_real_TDATA_int_regslice = s_axis_iq_TDATA_int_regslice[15:0];

assign m_axis_real_TVALID = regslice_both_m_axis_real_U_vld_out;

assign s_axis_iq_TREADY = regslice_both_s_axis_iq_V_data_V_U_ack_in;


reg find_kernel_block = 0;
// synthesis translate_off
`include "iq_to_real_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //iq_to_real

