domain_path: C:\TDM_0704\TDM_0704\radar_platform\export\radar_platform\sw\standalone_psu_cortexa53_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
