-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
-- 67d7842dbbe25473c3c32b93c0da8047785f30d78e8a024de1b57352245f9689

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lfm_tdm_gen_bitset_4ns_4ns_32ns_1s_4_1_1 is
generic (
    ADDRWIDTH : INTEGER := 32;
    DATAWIDTH : INTEGER := 4
);
port (

    sel   : in std_logic_vector (ADDRWIDTH-1 downto 0);
    din   : in std_logic_vector (DATAWIDTH-1 downto 0);
    value : in std_logic_vector (0 downto 0);
    dout  : out std_logic_vector (DATAWIDTH-1 downto 0)
);
end entity;

architecture behav of lfm_tdm_gen_bitset_4ns_4ns_32ns_1s_4_1_1 is
    signal dout_tmp : std_logic_vector (DATAWIDTH-1 downto 0);



begin

    process(din,sel,value) is
    begin
        dout_tmp <= din;
        if to_integer(unsigned(sel)) >= din'low and to_integer(unsigned(sel)) <= din'high then
            dout_tmp(to_integer(unsigned(sel))) <= value(0);
        end if;
    end process;


    dout <= dout_tmp;






end architecture;
