-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lfm_tdm_gen is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axis_tx_TREADY : IN STD_LOGIC;
    m_axis_tx_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_tx_TVALID : OUT STD_LOGIC;
    m_axis_tx_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_tx_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_tx_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    dbg_lfm_i : OUT STD_LOGIC_VECTOR (15 downto 0);
    dbg_lfm_q : OUT STD_LOGIC_VECTOR (15 downto 0);
    dbg_tx_sel : OUT STD_LOGIC_VECTOR (1 downto 0);
    dbg_chirp_count : OUT STD_LOGIC_VECTOR (15 downto 0);
    dbg_sample_count : OUT STD_LOGIC_VECTOR (15 downto 0);
    dbg_chirp_start : OUT STD_LOGIC_VECTOR (0 downto 0);
    dbg_chirp_end : OUT STD_LOGIC_VECTOR (0 downto 0);
    dbg_enable : OUT STD_LOGIC_VECTOR (0 downto 0);
    dbg_state : OUT STD_LOGIC_VECTOR (2 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of lfm_tdm_gen is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "lfm_tdm_gen_lfm_tdm_gen,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu48dr-fsvg1517-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.412000,HLS_SYN_LAT=4107,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=368,HLS_SYN_LUT=426,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000011";
    constant ap_const_lv16_3FF : STD_LOGIC_VECTOR (15 downto 0) := "0000001111111111";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv12_3E8 : STD_LOGIC_VECTOR (11 downto 0) := "001111101000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal regslice_both_m_axis_tx_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln53_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal m_axis_tx_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal chirp_2_fu_270_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln60_fu_290_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln60_reg_435 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln60_reg_435_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln60_reg_435_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln60_reg_435_pp0_iter3_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln60_reg_435_pp0_iter4_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln60_reg_435_pp0_iter5_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln60_reg_435_pp0_iter6_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln60_reg_435_pp0_iter7_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal tx_word_last_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_word_last_reg_440 : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_word_last_reg_440_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_word_last_reg_440_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_word_last_reg_440_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_word_last_reg_440_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_word_last_reg_440_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_word_last_reg_440_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_word_last_reg_440_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_word_last_reg_440_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_reg_445 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_450 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_450_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_450_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_450_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_450_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_450_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_450_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_450_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_450_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_450_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln62_fu_363_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln62_reg_464 : STD_LOGIC_VECTOR (15 downto 0);
    signal q_val_fu_369_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal q_val_reg_469 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_phi_mux_icmp_ln577_phi_fu_223_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal indvar_flatten2_fu_116 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln53_fu_312_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten2_load : STD_LOGIC_VECTOR (11 downto 0);
    signal chirp3_fu_120 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ap_sig_allocacmp_chirp3_load : STD_LOGIC_VECTOR (2 downto 0);
    signal sample4_fu_124 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal sample_fu_306_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_sample4_load : STD_LOGIC_VECTOR (10 downto 0);
    signal chirp_18_fu_128 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal chirp_fu_324_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_chirp_18_load : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal select_ln53_fu_262_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal cmp13_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln79_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_278_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_392_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln62_1_fu_366_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal word_fu_375_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal grp_fu_392_p0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_392_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_392_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_278_ce : STD_LOGIC;
    signal grp_fu_392_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal m_axis_tx_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal m_axis_tx_TVALID_int_regslice : STD_LOGIC;
    signal m_axis_tx_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_m_axis_tx_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_tx_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_tx_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_tx_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_tx_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_tx_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_tx_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_tx_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_tx_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_tx_V_last_V_U_vld_out : STD_LOGIC;
    signal grp_fu_392_p10 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_392_p20 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_condition_438 : BOOLEAN;
    signal ap_condition_150 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component lfm_tdm_gen_urem_3ns_3ns_3_7_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component lfm_tdm_gen_mac_muladd_10ns_3ns_10ns_12_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        din2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component lfm_tdm_gen_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component lfm_tdm_gen_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component lfm_tdm_gen_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    CTRL_s_axi_U : component lfm_tdm_gen_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    urem_3ns_3ns_3_7_1_U1 : component lfm_tdm_gen_urem_3ns_3ns_3_7_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => chirp_2_fu_270_p3,
        din1 => ap_const_lv3_3,
        ce => grp_fu_278_ce,
        dout => grp_fu_278_p2);

    mac_muladd_10ns_3ns_10ns_12_4_1_U2 : component lfm_tdm_gen_mac_muladd_10ns_3ns_10ns_12_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 10,
        din1_WIDTH => 3,
        din2_WIDTH => 10,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_392_p0,
        din1 => grp_fu_392_p1,
        din2 => grp_fu_392_p2,
        ce => grp_fu_392_ce,
        dout => grp_fu_392_p3);

    flow_control_loop_pipe_U : component lfm_tdm_gen_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);

    regslice_both_m_axis_tx_V_data_V_U : component lfm_tdm_gen_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_tx_TDATA_int_regslice,
        vld_in => m_axis_tx_TVALID_int_regslice,
        ack_in => m_axis_tx_TREADY_int_regslice,
        data_out => m_axis_tx_TDATA,
        vld_out => regslice_both_m_axis_tx_V_data_V_U_vld_out,
        ack_out => m_axis_tx_TREADY,
        apdone_blk => regslice_both_m_axis_tx_V_data_V_U_apdone_blk);

    regslice_both_m_axis_tx_V_keep_V_U : component lfm_tdm_gen_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => m_axis_tx_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_tx_V_keep_V_U_ack_in_dummy,
        data_out => m_axis_tx_TKEEP,
        vld_out => regslice_both_m_axis_tx_V_keep_V_U_vld_out,
        ack_out => m_axis_tx_TREADY,
        apdone_blk => regslice_both_m_axis_tx_V_keep_V_U_apdone_blk);

    regslice_both_m_axis_tx_V_strb_V_U : component lfm_tdm_gen_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => m_axis_tx_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_tx_V_strb_V_U_ack_in_dummy,
        data_out => m_axis_tx_TSTRB,
        vld_out => regslice_both_m_axis_tx_V_strb_V_U_vld_out,
        ack_out => m_axis_tx_TREADY,
        apdone_blk => regslice_both_m_axis_tx_V_strb_V_U_apdone_blk);

    regslice_both_m_axis_tx_V_last_V_U : component lfm_tdm_gen_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tx_word_last_reg_440_pp0_iter8_reg,
        vld_in => m_axis_tx_TVALID_int_regslice,
        ack_in => regslice_both_m_axis_tx_V_last_V_U_ack_in_dummy,
        data_out => m_axis_tx_TLAST,
        vld_out => regslice_both_m_axis_tx_V_last_V_U_vld_out,
        ack_out => m_axis_tx_TREADY,
        apdone_blk => regslice_both_m_axis_tx_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter10_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter10_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
            end if; 
        end if;
    end process;

    chirp3_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_150)) then
                chirp3_fu_120 <= chirp_2_fu_270_p3;
            end if;
        end if;
    end process;

    chirp_18_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_150)) then
                chirp_18_fu_128 <= chirp_fu_324_p2;
            end if;
        end if;
    end process;

    indvar_flatten2_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_150)) then
                indvar_flatten2_fu_116 <= add_ln53_fu_312_p2;
            end if;
        end if;
    end process;

    sample4_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_150)) then
                sample4_fu_124 <= sample_fu_306_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln53_reg_450 <= icmp_ln53_fu_330_p2;
                icmp_ln53_reg_450_pp0_iter1_reg <= icmp_ln53_reg_450;
                trunc_ln60_reg_435 <= trunc_ln60_fu_290_p1;
                trunc_ln60_reg_435_pp0_iter1_reg <= trunc_ln60_reg_435;
                tx_word_last_reg_440 <= tx_word_last_fu_300_p2;
                tx_word_last_reg_440_pp0_iter1_reg <= tx_word_last_reg_440;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln53_reg_450_pp0_iter2_reg <= icmp_ln53_reg_450_pp0_iter1_reg;
                icmp_ln53_reg_450_pp0_iter3_reg <= icmp_ln53_reg_450_pp0_iter2_reg;
                icmp_ln53_reg_450_pp0_iter4_reg <= icmp_ln53_reg_450_pp0_iter3_reg;
                icmp_ln53_reg_450_pp0_iter5_reg <= icmp_ln53_reg_450_pp0_iter4_reg;
                icmp_ln53_reg_450_pp0_iter6_reg <= icmp_ln53_reg_450_pp0_iter5_reg;
                icmp_ln53_reg_450_pp0_iter7_reg <= icmp_ln53_reg_450_pp0_iter6_reg;
                icmp_ln53_reg_450_pp0_iter8_reg <= icmp_ln53_reg_450_pp0_iter7_reg;
                icmp_ln53_reg_450_pp0_iter9_reg <= icmp_ln53_reg_450_pp0_iter8_reg;
                q_val_reg_469 <= q_val_fu_369_p2;
                trunc_ln60_reg_435_pp0_iter2_reg <= trunc_ln60_reg_435_pp0_iter1_reg;
                trunc_ln60_reg_435_pp0_iter3_reg <= trunc_ln60_reg_435_pp0_iter2_reg;
                trunc_ln60_reg_435_pp0_iter4_reg <= trunc_ln60_reg_435_pp0_iter3_reg;
                trunc_ln60_reg_435_pp0_iter5_reg <= trunc_ln60_reg_435_pp0_iter4_reg;
                trunc_ln60_reg_435_pp0_iter6_reg <= trunc_ln60_reg_435_pp0_iter5_reg;
                trunc_ln60_reg_435_pp0_iter7_reg <= trunc_ln60_reg_435_pp0_iter6_reg;
                tx_word_last_reg_440_pp0_iter2_reg <= tx_word_last_reg_440_pp0_iter1_reg;
                tx_word_last_reg_440_pp0_iter3_reg <= tx_word_last_reg_440_pp0_iter2_reg;
                tx_word_last_reg_440_pp0_iter4_reg <= tx_word_last_reg_440_pp0_iter3_reg;
                tx_word_last_reg_440_pp0_iter5_reg <= tx_word_last_reg_440_pp0_iter4_reg;
                tx_word_last_reg_440_pp0_iter6_reg <= tx_word_last_reg_440_pp0_iter5_reg;
                tx_word_last_reg_440_pp0_iter7_reg <= tx_word_last_reg_440_pp0_iter6_reg;
                tx_word_last_reg_440_pp0_iter8_reg <= tx_word_last_reg_440_pp0_iter7_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln57_reg_445 <= icmp_ln57_fu_318_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
                    zext_ln62_reg_464(11 downto 0) <= zext_ln62_fu_363_p1(11 downto 0);
            end if;
        end if;
    end process;
    zext_ln62_reg_464(15 downto 12) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln53_fu_312_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten2_load) + unsigned(ap_const_lv12_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_block_state10_pp0_stage0_iter9, regslice_both_m_axis_tx_V_data_V_U_apdone_blk, ap_block_state11_pp0_stage0_iter10, ap_loop_exit_ready_pp0_iter10_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (regslice_both_m_axis_tx_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)));
    end process;


    ap_block_pp0_stage0_01001_grp0_assign_proc : process(regslice_both_m_axis_tx_V_data_V_U_apdone_blk, ap_loop_exit_ready_pp0_iter10_reg)
    begin
                ap_block_pp0_stage0_01001_grp0 <= ((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (regslice_both_m_axis_tx_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_block_state10_pp0_stage0_iter9, regslice_both_m_axis_tx_V_data_V_U_apdone_blk, ap_block_state11_pp0_stage0_iter10, ap_loop_exit_ready_pp0_iter10_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (regslice_both_m_axis_tx_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_block_state10_pp0_stage0_iter9, regslice_both_m_axis_tx_V_data_V_U_apdone_blk, ap_block_state11_pp0_stage0_iter10, ap_loop_exit_ready_pp0_iter10_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (regslice_both_m_axis_tx_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)));
    end process;


    ap_block_pp0_stage0_subdone_grp0_assign_proc : process(regslice_both_m_axis_tx_V_data_V_U_apdone_blk, ap_loop_exit_ready_pp0_iter10_reg)
    begin
                ap_block_pp0_stage0_subdone_grp0 <= ((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (regslice_both_m_axis_tx_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(m_axis_tx_TREADY_int_regslice)
    begin
                ap_block_state10_pp0_stage0_iter9 <= (m_axis_tx_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state11_pp0_stage0_iter10_assign_proc : process(regslice_both_m_axis_tx_V_data_V_U_apdone_blk, m_axis_tx_TREADY_int_regslice)
    begin
                ap_block_state11_pp0_stage0_iter10 <= ((regslice_both_m_axis_tx_V_data_V_U_apdone_blk = ap_const_logic_1) or (m_axis_tx_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_150_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_150 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_438_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln53_reg_450)
    begin
                ap_condition_438 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln53_reg_450 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln53_fu_330_p2)
    begin
        if (((icmp_ln53_fu_330_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_loop_exit_ready_pp0_iter10_reg, ap_block_pp0_stage0_subdone, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_icmp_ln577_phi_fu_223_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln57_reg_445, ap_loop_init, ap_condition_438)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_438)) then 
                ap_phi_mux_icmp_ln577_phi_fu_223_p4 <= icmp_ln57_reg_445;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln577_phi_fu_223_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln577_phi_fu_223_p4 <= icmp_ln57_reg_445;
            end if;
        else 
            ap_phi_mux_icmp_ln577_phi_fu_223_p4 <= icmp_ln57_reg_445;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_chirp3_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, chirp3_fu_120)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_chirp3_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_chirp3_load <= chirp3_fu_120;
        end if; 
    end process;


    ap_sig_allocacmp_chirp_18_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, chirp_18_fu_128)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_chirp_18_load <= ap_const_lv3_1;
        else 
            ap_sig_allocacmp_chirp_18_load <= chirp_18_fu_128;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten2_fu_116)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten2_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten2_load <= indvar_flatten2_fu_116;
        end if; 
    end process;


    ap_sig_allocacmp_sample4_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, sample4_fu_124)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_sample4_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_sample4_load <= sample4_fu_124;
        end if; 
    end process;

    chirp_2_fu_270_p3 <= 
        ap_sig_allocacmp_chirp_18_load when (ap_phi_mux_icmp_ln577_phi_fu_223_p4(0) = '1') else 
        ap_sig_allocacmp_chirp3_load;
    chirp_fu_324_p2 <= std_logic_vector(unsigned(chirp_2_fu_270_p3) + unsigned(ap_const_lv3_1));
    cmp13_fu_284_p2 <= "1" when (chirp_2_fu_270_p3 = ap_const_lv3_3) else "0";
    dbg_chirp_count <= ap_const_lv16_3;
    dbg_chirp_end <= ap_const_lv1_1;
    dbg_chirp_start <= ap_const_lv1_0;
    dbg_enable <= ap_const_lv1_0;
    dbg_lfm_i <= zext_ln62_reg_464;
        dbg_lfm_q <= std_logic_vector(IEEE.numeric_std.resize(signed(q_val_reg_469),16));

    dbg_sample_count <= ap_const_lv16_3FF;
    dbg_state <= ap_const_lv3_0;
    dbg_tx_sel <= ap_const_lv2_0;

    grp_fu_278_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_278_ce <= ap_const_logic_1;
        else 
            grp_fu_278_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_392_ce_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            grp_fu_392_ce <= ap_const_logic_1;
        else 
            grp_fu_392_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_392_p0 <= ap_const_lv12_3E8(10 - 1 downto 0);
    grp_fu_392_p1 <= grp_fu_392_p10(3 - 1 downto 0);
    grp_fu_392_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_278_p2),12));
    grp_fu_392_p2 <= grp_fu_392_p20(10 - 1 downto 0);
    grp_fu_392_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln60_reg_435_pp0_iter7_reg),12));
    icmp_ln53_fu_330_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten2_load = ap_const_lv12_FFF) else "0";
    icmp_ln57_fu_318_p2 <= "1" when (sample_fu_306_p2 = ap_const_lv11_400) else "0";
    icmp_ln79_fu_294_p2 <= "1" when (select_ln53_fu_262_p3 = ap_const_lv11_3FF) else "0";

    m_axis_tx_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_block_pp0_stage0, m_axis_tx_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)))) then 
            m_axis_tx_TDATA_blk_n <= m_axis_tx_TREADY_int_regslice;
        else 
            m_axis_tx_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        m_axis_tx_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(signed(word_fu_375_p3),32));

    m_axis_tx_TVALID <= regslice_both_m_axis_tx_V_data_V_U_vld_out;

    m_axis_tx_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            m_axis_tx_TVALID_int_regslice <= ap_const_logic_1;
        else 
            m_axis_tx_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    q_val_fu_369_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(zext_ln62_1_fu_366_p1));
    sample_fu_306_p2 <= std_logic_vector(unsigned(select_ln53_fu_262_p3) + unsigned(ap_const_lv11_1));
    select_ln53_fu_262_p3 <= 
        ap_const_lv11_0 when (ap_phi_mux_icmp_ln577_phi_fu_223_p4(0) = '1') else 
        ap_sig_allocacmp_sample4_load;
    trunc_ln60_fu_290_p1 <= select_ln53_fu_262_p3(10 - 1 downto 0);
    tx_word_last_fu_300_p2 <= (icmp_ln79_fu_294_p2 and cmp13_fu_284_p2);
    word_fu_375_p3 <= (q_val_fu_369_p2 & zext_ln62_fu_363_p1);
    zext_ln62_1_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_392_p3),13));
    zext_ln62_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_392_p3),16));
end behav;
