// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="lfm_tdm_gen_lfm_tdm_gen,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu48dr-fsvg1517-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.412000,HLS_SYN_LAT=4099,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=76,HLS_SYN_LUT=288,HLS_VERSION=2024_2}" *)

module lfm_tdm_gen (
        ap_clk,
        ap_rst_n,
        m_axis_tx_TREADY,
        m_axis_tx_TDATA,
        m_axis_tx_TVALID,
        m_axis_tx_TKEEP,
        m_axis_tx_TSTRB,
        m_axis_tx_TLAST,
        dbg_lfm_i,
        dbg_lfm_q,
        dbg_tx_sel,
        dbg_chirp_count,
        dbg_sample_count,
        dbg_chirp_start,
        dbg_chirp_end,
        dbg_enable,
        dbg_state,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   m_axis_tx_TREADY;
output  [31:0] m_axis_tx_TDATA;
output   m_axis_tx_TVALID;
output  [3:0] m_axis_tx_TKEEP;
output  [3:0] m_axis_tx_TSTRB;
output  [0:0] m_axis_tx_TLAST;
output  [15:0] dbg_lfm_i;
output  [15:0] dbg_lfm_q;
output  [1:0] dbg_tx_sel;
output  [15:0] dbg_chirp_count;
output  [15:0] dbg_sample_count;
output  [0:0] dbg_chirp_start;
output  [0:0] dbg_chirp_end;
output  [0:0] dbg_enable;
output  [2:0] dbg_state;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_ready;
reg    ap_block_state2_pp0_stage0_iter1;
wire    regslice_both_m_axis_tx_V_data_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln53_fu_342_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
wire   [9:0] LFM_IQ_LUT_address0;
wire   [30:0] LFM_IQ_LUT_q0;
reg    m_axis_tx_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tx_word_last_fu_312_p2;
reg   [0:0] tx_word_last_reg_406;
wire   [0:0] icmp_ln56_fu_330_p2;
reg   [0:0] icmp_ln56_reg_411;
reg   [0:0] icmp_ln53_reg_416;
reg   [0:0] icmp_ln53_reg_416_pp0_iter1_reg;
reg   [0:0] ap_phi_mux_icmp_ln565_phi_fu_240_p4;
wire    ap_loop_init;
wire   [63:0] zext_ln56_fu_301_p1;
reg   [11:0] indvar_flatten2_fu_118;
wire   [11:0] add_ln53_fu_324_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten2_load;
reg   [2:0] chirp3_fu_122;
wire   [2:0] chirp_2_fu_287_p3;
reg   [2:0] ap_sig_allocacmp_chirp3_load;
reg   [10:0] sample4_fu_126;
wire   [10:0] sample_fu_318_p2;
reg   [10:0] ap_sig_allocacmp_sample4_load;
reg   [2:0] chirp_16_fu_130;
wire   [2:0] chirp_fu_336_p2;
reg   [2:0] ap_sig_allocacmp_chirp_16_load;
reg    ap_block_pp0_stage0_01001;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage0_01001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
reg    ap_block_pp0_stage0_subdone_grp0;
reg    LFM_IQ_LUT_ce0_local;
wire   [10:0] select_ln53_fu_279_p3;
wire   [0:0] cmp13_fu_295_p2;
wire   [0:0] icmp_ln72_fu_306_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [31:0] m_axis_tx_TDATA_int_regslice;
reg    m_axis_tx_TVALID_int_regslice;
wire    m_axis_tx_TREADY_int_regslice;
wire    regslice_both_m_axis_tx_V_data_V_U_vld_out;
wire    regslice_both_m_axis_tx_V_keep_V_U_apdone_blk;
wire    regslice_both_m_axis_tx_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_tx_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_tx_V_strb_V_U_apdone_blk;
wire    regslice_both_m_axis_tx_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_tx_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_tx_V_last_V_U_apdone_blk;
wire    regslice_both_m_axis_tx_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_tx_V_last_V_U_vld_out;
reg    ap_condition_326;
reg    ap_condition_110;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 indvar_flatten2_fu_118 = 12'd0;
#0 chirp3_fu_122 = 3'd0;
#0 sample4_fu_126 = 11'd0;
#0 chirp_16_fu_130 = 3'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

lfm_tdm_gen_LFM_IQ_LUT_ROM_AUTO_1R #(
    .DataWidth( 31 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
LFM_IQ_LUT_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(LFM_IQ_LUT_address0),
    .ce0(LFM_IQ_LUT_ce0_local),
    .q0(LFM_IQ_LUT_q0)
);

lfm_tdm_gen_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

lfm_tdm_gen_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

lfm_tdm_gen_regslice_both #(
    .DataWidth( 32 ))
regslice_both_m_axis_tx_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_tx_TDATA_int_regslice),
    .vld_in(m_axis_tx_TVALID_int_regslice),
    .ack_in(m_axis_tx_TREADY_int_regslice),
    .data_out(m_axis_tx_TDATA),
    .vld_out(regslice_both_m_axis_tx_V_data_V_U_vld_out),
    .ack_out(m_axis_tx_TREADY),
    .apdone_blk(regslice_both_m_axis_tx_V_data_V_U_apdone_blk)
);

lfm_tdm_gen_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_tx_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(m_axis_tx_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_tx_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_tx_TKEEP),
    .vld_out(regslice_both_m_axis_tx_V_keep_V_U_vld_out),
    .ack_out(m_axis_tx_TREADY),
    .apdone_blk(regslice_both_m_axis_tx_V_keep_V_U_apdone_blk)
);

lfm_tdm_gen_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_tx_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(m_axis_tx_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_tx_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_tx_TSTRB),
    .vld_out(regslice_both_m_axis_tx_V_strb_V_U_vld_out),
    .ack_out(m_axis_tx_TREADY),
    .apdone_blk(regslice_both_m_axis_tx_V_strb_V_U_apdone_blk)
);

lfm_tdm_gen_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_tx_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tx_word_last_reg_406),
    .vld_in(m_axis_tx_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_tx_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_tx_TLAST),
    .vld_out(regslice_both_m_axis_tx_V_last_V_U_vld_out),
    .ack_out(m_axis_tx_TREADY),
    .apdone_blk(regslice_both_m_axis_tx_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_110)) begin
        chirp3_fu_122 <= chirp_2_fu_287_p3;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_110)) begin
    chirp_16_fu_130 <= chirp_fu_336_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_110)) begin
    indvar_flatten2_fu_118 <= add_ln53_fu_324_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_110)) begin
    sample4_fu_126 <= sample_fu_318_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln53_reg_416 <= icmp_ln53_fu_342_p2;
        icmp_ln53_reg_416_pp0_iter1_reg <= icmp_ln53_reg_416;
        tx_word_last_reg_406 <= tx_word_last_fu_312_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln56_reg_411 <= icmp_ln56_fu_330_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        LFM_IQ_LUT_ce0_local = 1'b1;
    end else begin
        LFM_IQ_LUT_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln53_fu_342_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_326)) begin
            ap_phi_mux_icmp_ln565_phi_fu_240_p4 = icmp_ln56_reg_411;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln565_phi_fu_240_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln565_phi_fu_240_p4 = icmp_ln56_reg_411;
        end
    end else begin
        ap_phi_mux_icmp_ln565_phi_fu_240_p4 = icmp_ln56_reg_411;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_chirp3_load = 3'd0;
    end else begin
        ap_sig_allocacmp_chirp3_load = chirp3_fu_122;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_chirp_16_load = 3'd1;
    end else begin
        ap_sig_allocacmp_chirp_16_load = chirp_16_fu_130;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten2_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten2_load = indvar_flatten2_fu_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sample4_load = 11'd0;
    end else begin
        ap_sig_allocacmp_sample4_load = sample4_fu_126;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        m_axis_tx_TDATA_blk_n = m_axis_tx_TREADY_int_regslice;
    end else begin
        m_axis_tx_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_tx_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_tx_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LFM_IQ_LUT_address0 = zext_ln56_fu_301_p1;

assign add_ln53_fu_324_p2 = (ap_sig_allocacmp_indvar_flatten2_load + 12'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_m_axis_tx_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp0 = ((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_m_axis_tx_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_m_axis_tx_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_m_axis_tx_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp0 = ((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_m_axis_tx_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (m_axis_tx_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_m_axis_tx_V_data_V_U_apdone_blk == 1'b1) | (m_axis_tx_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_condition_110 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_326 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln53_reg_416 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign chirp_2_fu_287_p3 = ((ap_phi_mux_icmp_ln565_phi_fu_240_p4[0:0] == 1'b1) ? ap_sig_allocacmp_chirp_16_load : ap_sig_allocacmp_chirp3_load);

assign chirp_fu_336_p2 = (chirp_2_fu_287_p3 + 3'd1);

assign cmp13_fu_295_p2 = ((chirp_2_fu_287_p3 == 3'd3) ? 1'b1 : 1'b0);

assign dbg_chirp_count = 16'd3;

assign dbg_chirp_end = 1'd1;

assign dbg_chirp_start = 1'd0;

assign dbg_enable = 1'd0;

assign dbg_lfm_i = 16'd53749;

assign dbg_lfm_q = 16'd63287;

assign dbg_sample_count = 16'd1023;

assign dbg_state = 3'd0;

assign dbg_tx_sel = 2'd0;

assign icmp_ln53_fu_342_p2 = ((ap_sig_allocacmp_indvar_flatten2_load == 12'd4095) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_330_p2 = ((sample_fu_318_p2 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_306_p2 = ((select_ln53_fu_279_p3 == 11'd1023) ? 1'b1 : 1'b0);

assign m_axis_tx_TDATA_int_regslice = $signed(LFM_IQ_LUT_q0);

assign m_axis_tx_TVALID = regslice_both_m_axis_tx_V_data_V_U_vld_out;

assign sample_fu_318_p2 = (select_ln53_fu_279_p3 + 11'd1);

assign select_ln53_fu_279_p3 = ((ap_phi_mux_icmp_ln565_phi_fu_240_p4[0:0] == 1'b1) ? 11'd0 : ap_sig_allocacmp_sample4_load);

assign tx_word_last_fu_312_p2 = (icmp_ln72_fu_306_p2 & cmp13_fu_295_p2);

assign zext_ln56_fu_301_p1 = select_ln53_fu_279_p3;

endmodule //lfm_tdm_gen
